# Nome do fluxo de trabalho
name: Stop Instance EC2 Ubuntu

on:
  workflow_dispatch:  # Evento manual de acionamento da pipeline
    inputs:
      environment:
        description: 'Environment to deploy to'  # Descrição do input
        required: true
        default: 'stoping'  # Valor padrão
      version:
        description: 'Version of the app to deploy'
        required: true
        default: 'v1.0'
jobs:
  # Definição do job
  deploy:
    # Ambiente onde o job será executado
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar as credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_EC2_KEY_ID }}  # ID da chave de acesso AWS
          aws-secret-access-key: ${{ secrets.AWS_EC2_SECRET_ACCESS_KEY }}  # Chave secreta de acesso AWS
          aws-region: us-east-1  # Região da AWS (pode ser alterada conforme necessário)
      # Passo 3 : Desligar a Instancia
      - name: Stop EC2 Instance
        run: |
          aws ec2 stop-instances --instance-ids i-0bf3914003b413e0c
          echo "Instance stoped successfully."
